// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'episodeNumber': string;
  'multiple': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
